files:
  include: 'source/**/*.scss'
rules:
  class-name-format:
    - 1
    -
      convention: hyphenatedbem
  indentation:
    - 1
    -
      size: 4
  nesting-depth:
    - 1
    -
      max-depth: 3
  property-sort-order:
    - 1
    -
      order: smacss
